alias lazyvim="NVIM_APPNAME=lazyvim nvim"
alias astrovim="NVIM_APPNAME=astrovim nvim"
alias lunarvim="NVIM_APPNAME=lunarvim nvim"
alias nvimchad="NVIM_APPNAME=nvimchad nvim"
# alias knvim="NVIM_APPNAME="nvim-kickstart" nvim"
alias bv="NVIM_APPNAME=bvim nvim"
alias vi="NVIM_APPNAME=lazyvim nvim"
